Repository back-og/back-log, pull requests merged in 2023-09, with the labels that each got.

#56 최신 순서로 게시글 목록 조회 기능 구현
  build.gradle
  src/main/java/dev/backlog/domain/auth/api/AuthController.java
  src/main/java/dev/backlog/domain/auth/infrastructure/kakao/client/KakaoMemberClient.java
  src/main/java/dev/backlog/domain/auth/model/oauth/client/OAuthMemberClientComposite.java
  src/main/java/dev/backlog/domain/auth/service/OAuthService.java
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/test/java/dev/backlog/common/fixture/TestFixture.java
  src/test/java/dev/backlog/common/util/TestFixtureUtil.java
  src/test/java/dev/backlog/domain/auth/service/OAuthServiceTest.java
  src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepositoryTest.java
  src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepositoryTest.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostHashtagRepositoryTest.java
  src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostRepositoryTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
Labels: ✏️ Feature

#60 트렌딩 조회 기능 구현
  src/main/java/dev/backlog/common/config/QueryDslConfig.java
  src/main/java/dev/backlog/domain/auth/api/AuthController.java
  src/main/java/dev/backlog/domain/like/model/Like.java
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepository.java
  src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepositoryImpl.java
  src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostRepository.java
  src/main/java/dev/backlog/domain/post/model/Post.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/main/resources/application.yml
  src/test/java/dev/backlog/common/RepositoryTest.java
  src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepositoryTest.java
  src/test/java/dev/backlog/domain/hashtag/infrastructure/persistence/HashtagRepositoryTest.java
  src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepositoryTest.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostHashtagRepositoryTest.java
  src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepositoryImplTest.java
  src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostRepositoryTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
  src/test/java/dev/backlog/domain/series/infrastructure/persistence/SeriesRepositoryTest.java
  src/test/resources/application.yml
Labels: ✏️ Feature

#63 사용자 프로필 수정 기능 구현
  src/main/java/dev/backlog/domain/user/api/UserController.java
  src/main/java/dev/backlog/domain/user/dto/UserDetailsResponse.java
  src/main/java/dev/backlog/domain/user/dto/UserResponse.java
  src/main/java/dev/backlog/domain/user/dto/UserUpdateRequest.java
  src/main/java/dev/backlog/domain/user/infrastructure/persistence/UserRepository.java
  src/main/java/dev/backlog/domain/user/model/User.java
  src/main/java/dev/backlog/domain/user/service/UserService.java
  src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
  src/test/java/dev/backlog/domain/user/service/UserServiceTest.java
Labels: ✏️ Feature

#68 닉네임 + 해쉬태그를 통한 게시물 검색
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepository.java
  src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepositoryImpl.java
  src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostRepository.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepositoryImplTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
Labels: ✏️ Feature

#67 ArgumentResolver 적용
  src/main/java/dev/backlog/common/UserArgumentResolver.java
  src/main/java/dev/backlog/common/config/AuthWebConfig.java
  src/main/java/dev/backlog/domain/user/api/UserController.java
  src/main/java/dev/backlog/domain/user/dto/UserPrincipal.java
  src/main/java/dev/backlog/domain/user/service/UserService.java
  src/test/java/dev/backlog/common/config/ControllerTestConfig.java
  src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
  src/test/java/dev/backlog/domain/user/service/UserServiceTest.java
Labels: ✏️ Feature

#72 Post 도메인을 페어프로그래밍으로 리팩터링
  src/main/java/dev/backlog/common/UserArgumentResolver.java
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/infra/PostRepositoryAdapter.java
  src/main/java/dev/backlog/domain/post/infra/jpa/PostHashtagRepository.java
  src/main/java/dev/backlog/domain/post/infra/jpa/PostJpaRepository.java
  src/main/java/dev/backlog/domain/post/infra/jpa/query/PostQueryDslRepositoryImpl.java
  src/main/java/dev/backlog/domain/post/model/repository/PostQueryRepository.java
  src/main/java/dev/backlog/domain/post/model/repository/PostRepository.java
  src/main/java/dev/backlog/domain/post/service/PostHashtagService.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/main/java/dev/backlog/domain/user/api/UserController.java
  src/main/java/dev/backlog/domain/user/dto/AuthInfo.java
  src/main/java/dev/backlog/domain/user/dto/UserPrincipal.java
  src/test/java/dev/backlog/common/RepositoryTest.java
  src/test/java/dev/backlog/common/config/ControllerTestConfig.java
  src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepositoryTest.java
  src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepositoryTest.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostHashtagRepositoryTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostQueryDslRepositoryImplTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostRepositoryTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
Labels: 🧚 Refactor

#73 Post 도메인 Service 분리
  src/main/java/dev/backlog/domain/auth/service/OAuthService.java
  src/main/java/dev/backlog/domain/comment/infrastructure/persistence/CommentJpaRepository.java
  src/main/java/dev/backlog/domain/hashtag/infrastructure/persistence/HashtagJpaRepository.java
  src/main/java/dev/backlog/domain/like/infrastructure/persistence/LikeJpaRepository.java
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/infra/PostHashtagRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/post/infra/PostRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/post/infra/jpa/PostHashtagJpaRepository.java
  src/main/java/dev/backlog/domain/post/model/repository/PostHashtagRepository.java
  src/main/java/dev/backlog/domain/post/service/PostHashtagService.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/main/java/dev/backlog/domain/post/service/query/PostQueryService.java
  src/main/java/dev/backlog/domain/series/infrastructure/persistence/SeriesJpaRepository.java
  src/main/java/dev/backlog/domain/user/infrastructure/persistence/UserJpaRepository.java
  src/main/java/dev/backlog/domain/user/service/UserService.java
  src/test/java/dev/backlog/common/RepositoryTest.java
  src/test/java/dev/backlog/common/config/TestContainerConfig.java
  src/test/java/dev/backlog/domain/auth/service/OAuthServiceTest.java
  src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/hashtag/infrastructure/persistence/HashtagJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostHashtagJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostQueryDslRepositoryImplTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostRepositoryTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
  src/test/java/dev/backlog/domain/post/service/query/PostQueryServiceTest.java
  src/test/java/dev/backlog/domain/series/infrastructure/persistence/SeriesJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/user/service/UserServiceTest.java
Labels: 🧚 Refactor

#75 예외 처리 기능
  src/main/java/dev/backlog/common/advice/ErrorResponse.java
  src/main/java/dev/backlog/common/advice/GlobalExceptionHandler.java
  src/main/java/dev/backlog/common/exception/BackLogException.java
  src/main/java/dev/backlog/common/exception/ErrorCode.java
  src/main/java/dev/backlog/common/exception/NotFoundException.java
  src/main/java/dev/backlog/domain/user/exception/UserErrorCode.java
Labels: ✏️ Feature

#78 RedisRepository 설정
  src/main/java/dev/backlog/common/config/RedisConfig.java
  src/main/java/dev/backlog/domain/post/infra/PostCacheRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/post/infra/redis/PostRedisRepository.java
  src/main/java/dev/backlog/domain/post/model/Post.java
  src/main/java/dev/backlog/domain/post/model/ViewHistory.java
  src/main/java/dev/backlog/domain/post/model/repository/PostCacheRepository.java
  src/main/java/dev/backlog/domain/post/service/query/PostQueryService.java
  src/test/java/dev/backlog/common/RepositoryTest.java
  src/test/java/dev/backlog/domain/post/model/repository/PostCacheRepositoryTest.java
Labels: 🧚 Refactor

#81 게시물 생성 API 리팩터링
  src/main/java/dev/backlog/domain/post/dto/PostCreateRequest.java
  src/main/java/dev/backlog/domain/post/dto/PostUpdateRequest.java
  src/main/java/dev/backlog/domain/post/model/Post.java
  src/main/java/dev/backlog/domain/post/service/PostHashtagService.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/test/java/dev/backlog/common/config/ControllerTestConfig.java
  src/test/java/dev/backlog/common/fixture/DtoFixture.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
Labels: 🧚 Refactor

#84 Post 도메인 리팩토링
  src/main/java/dev/backlog/domain/comment/infra/CommentRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/comment/infra/jpa/CommentJpaRepository.java
  src/main/java/dev/backlog/domain/comment/model/repository/CommentRepository.java
  src/main/java/dev/backlog/domain/like/infra/LikeRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/like/infra/jpa/LikeJpaRepository.java
  src/main/java/dev/backlog/domain/like/model/repository/LikeRepository.java
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/infra/PostCacheRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/post/infra/PostRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/post/infra/redis/PostRedisRepository.java
  src/main/java/dev/backlog/domain/post/model/UserViewInfo.java
  src/main/java/dev/backlog/domain/post/model/repository/PostCacheRepository.java
  src/main/java/dev/backlog/domain/post/model/repository/PostRepository.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/main/java/dev/backlog/domain/post/service/query/PostQueryService.java
  src/main/java/dev/backlog/domain/series/infra/SeriesRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/series/infra/jpa/SeriesJpaRepository.java
  src/main/java/dev/backlog/domain/series/model/repository/SeriesRepository.java
  src/test/java/dev/backlog/common/RepositoryTest.java
  src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/comment/model/repository/CommentRepositoryTest.java
  src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/like/model/repository/LikeRepositoryTest.java
  src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
  src/test/java/dev/backlog/domain/post/infra/jpa/PostHashtagJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/post/model/repository/PostCacheRepositoryTest.java
  src/test/java/dev/backlog/domain/post/model/repository/PostQueryRepositoryTest.java
  src/test/java/dev/backlog/domain/post/model/repository/PostRepositoryTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
  src/test/java/dev/backlog/domain/post/service/query/PostQueryServiceTest.java
  src/test/java/dev/backlog/domain/series/infrastructure/persistence/SeriesJpaRepositoryTest.java
  src/test/java/dev/backlog/domain/series/model/repository/SeriesRepositoryTest.java
Labels: 🧚 Refactor

#87 토큰 갱신 기능 구현
  src/main/java/dev/backlog/common/UserArgumentResolver.java
  src/main/java/dev/backlog/domain/auth/AuthTokensGenerator.java
  src/main/java/dev/backlog/domain/auth/api/AuthController.java
  src/main/java/dev/backlog/domain/auth/model/oauth/JwtTokenProvider.java
  src/main/java/dev/backlog/domain/auth/service/OAuthService.java
  src/main/java/dev/backlog/domain/user/dto/AuthInfo.java
  src/test/java/dev/backlog/domain/auth/api/AuthControllerTest.java
  src/test/java/dev/backlog/domain/auth/service/OAuthServiceTest.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
  src/test/java/dev/backlog/domain/post/service/query/PostQueryServiceTest.java
  src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
Labels: ✏️ Feature

#91 시리즈 생성 api 구현
  src/main/java/dev/backlog/common/advice/GlobalExceptionHandler.java
  src/main/java/dev/backlog/common/exception/GlobalErrorCode.java
  src/main/java/dev/backlog/domain/auth/model/oauth/JwtTokenProvider.java
  src/main/java/dev/backlog/domain/series/api/SeriesController.java
  src/main/java/dev/backlog/domain/series/dto/SeriesCreateRequest.java
  src/main/java/dev/backlog/domain/series/infra/SeriesRepositoryAdaptor.java
  src/main/java/dev/backlog/domain/series/model/repository/SeriesRepository.java
  src/main/java/dev/backlog/domain/series/service/SeriesService.java
  src/main/java/dev/backlog/domain/user/exception/UserErrorCode.java
  src/main/java/dev/backlog/domain/user/infrastructure/UserRepositoryAdapter.java
  src/test/java/dev/backlog/common/fixture/DtoFixture.java
  src/test/java/dev/backlog/domain/series/api/SeriesControllerTest.java
  src/test/java/dev/backlog/domain/series/infra/SeriesRepositoryAdaptorTest.java
  src/test/java/dev/backlog/domain/series/service/SeriesServiceTest.java
Labels: ✏️ Feature

#88 사용자 탈퇴 처리 기능 구현
  src/main/java/dev/backlog/domain/auth/infrastructure/kakao/client/KakaoApiClient.java
  src/main/java/dev/backlog/domain/auth/infrastructure/kakao/client/KakaoMemberClient.java
  src/main/java/dev/backlog/domain/auth/service/OAuthService.java
  src/main/java/dev/backlog/domain/user/api/UserController.java
  src/main/java/dev/backlog/domain/user/infrastructure/UserRepositoryAdapter.java
  src/main/java/dev/backlog/domain/user/model/User.java
  src/main/java/dev/backlog/domain/user/model/repository/UserRepository.java
  src/main/java/dev/backlog/domain/user/service/UserService.java
Labels: ✏️ Feature

#93 게시물 삭제 API 리팩토링
  src/main/java/dev/backlog/domain/post/api/PostController.java
  src/main/java/dev/backlog/domain/post/service/PostService.java
  src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
Labels: 🧚 Refactor

#99 사용자 중복 체크 기능 추가
  src/main/java/dev/backlog/auth/service/OAuthService.java
  src/main/java/dev/backlog/user/api/UserController.java
  src/main/java/dev/backlog/user/domain/repository/UserRepository.java
  src/main/java/dev/backlog/user/dto/UserDetailsResponse.java
  src/main/java/dev/backlog/user/dto/UserUpdateRequest.java
  src/main/java/dev/backlog/user/infrastructure/UserRepositoryAdapter.java
  src/test/java/dev/backlog/user/api/UserControllerTest.java
  src/test/java/dev/backlog/user/service/UserServiceTest.java
Labels: 🧚 Refactor

#103 예외처리 리팩터링
  src/main/java/dev/backlog/common/advice/ErrorResponse.java
  src/main/java/dev/backlog/common/advice/GlobalExceptionHandler.java
  src/main/java/dev/backlog/common/exception/ErrorCode.java
  src/main/java/dev/backlog/common/exception/GlobalErrorCode.java
  src/main/java/dev/backlog/user/exception/UserErrorCode.java
  src/main/java/dev/backlog/user/infrastructure/UserRepositoryAdapter.java
Labels: 🧚 Refactor

#108 Feature/#98
  src/main/java/dev/backlog/series/api/SeriesController.java
  src/main/java/dev/backlog/series/domain/Series.java
  src/main/java/dev/backlog/series/domain/repository/SeriesRepository.java
  src/main/java/dev/backlog/series/infra/SeriesRepositoryAdaptor.java
  src/main/java/dev/backlog/series/service/SeriesService.java
  src/test/java/dev/backlog/series/api/SeriesControllerTest.java
  src/test/java/dev/backlog/series/service/SeriesServiceTest.java
Labels: ✏️ Feature

#107 사용자 커스텀 예외 적용
  src/main/java/dev/backlog/auth/service/OAuthService.java
  src/main/java/dev/backlog/user/domain/repository/UserRepository.java
  src/main/java/dev/backlog/user/infrastructure/UserRepositoryAdapter.java
  src/main/java/dev/backlog/user/infrastructure/jpa/UserJpaRepository.java
Labels: 🧚 Refactor

#112 시리즈 목록 조회 api 구현
  src/main/java/dev/backlog/common/advice/ErrorResponse.java
  src/main/java/dev/backlog/common/advice/GlobalExceptionHandler.java
  src/main/java/dev/backlog/common/dto/SliceResponse.java
  src/main/java/dev/backlog/post/api/PostController.java
  src/main/java/dev/backlog/post/domain/repository/PostRepository.java
  src/main/java/dev/backlog/post/dto/PostSliceResponse.java
  src/main/java/dev/backlog/post/infra/PostRepositoryAdaptor.java
  src/main/java/dev/backlog/post/infra/jpa/PostJpaRepository.java
  src/main/java/dev/backlog/post/service/query/PostQueryService.java
  src/main/java/dev/backlog/series/api/SeriesController.java
  src/main/java/dev/backlog/series/domain/Series.java
  src/main/java/dev/backlog/series/domain/repository/SeriesRepository.java
  src/main/java/dev/backlog/series/dto/SeriesSummaryResponse.java
  src/main/java/dev/backlog/series/infra/SeriesRepositoryAdaptor.java
  src/main/java/dev/backlog/series/infra/jpa/SeriesJpaRepository.java
  src/main/java/dev/backlog/series/service/query/SeriesQueryService.java
  src/test/java/dev/backlog/common/fixture/EntityFixture.java
  src/test/java/dev/backlog/post/api/PostControllerTest.java
  src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
  src/test/java/dev/backlog/series/api/SeriesControllerTest.java
  src/test/java/dev/backlog/series/infra/SeriesRepositoryAdaptorTest.java
  src/test/java/dev/backlog/series/service/SeriesServiceTest.java
  src/test/java/dev/backlog/series/service/query/SeriesQueryServiceTest.java
  src/test/java/dev/backlog/user/service/UserServiceTest.java
Labels: ✏️ Feature

#110 Auth 커스텀 예외 적용
  src/main/java/dev/backlog/auth/domain/oauth/JwtTokenProvider.java
  src/main/java/dev/backlog/auth/domain/oauth/authcode/AuthCodeRequestUrlProviderComposite.java
  src/main/java/dev/backlog/auth/domain/oauth/client/OAuthMemberClientComposite.java
  src/main/java/dev/backlog/auth/exception/AuthErrorCode.java
  src/main/java/dev/backlog/auth/exception/AuthErrorMessage.java
  src/main/java/dev/backlog/auth/service/OAuthService.java
  src/main/java/dev/backlog/common/advice/GlobalExceptionHandler.java
  src/main/java/dev/backlog/common/exception/InvalidAuthException.java
  src/main/java/dev/backlog/user/infrastructure/jpa/UserJpaRepository.java
Labels: 🧚 Refactor

#115 프로필 사진 기본값 적용 구현
  src/main/java/dev/backlog/auth/service/OAuthService.java
Labels: 🧚 Refactor

#113 댓글 생성 기능 구현
  src/main/java/dev/backlog/comment/api/CommentController.java
  src/main/java/dev/backlog/comment/domain/repository/CommentRepository.java
  src/main/java/dev/backlog/comment/dto/CreateCommentRequest.java
  src/main/java/dev/backlog/comment/infra/CommentRepositoryAdaptor.java
  src/main/java/dev/backlog/comment/service/CommentService.java
  src/test/java/dev/backlog/comment/api/CommentControllerTest.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
Labels: ✏️ Feature

#111 게시물 좋아요 API 기능 개발
  src/main/java/dev/backlog/like/api/PostLikeController.java
  src/main/java/dev/backlog/like/domain/PostLike.java
  src/main/java/dev/backlog/like/domain/repository/LikeRepository.java
  src/main/java/dev/backlog/like/domain/repository/PostLikeRepository.java
  src/main/java/dev/backlog/like/dto/LikeStatus.java
  src/main/java/dev/backlog/like/infra/LikeRepositoryAdaptor.java
  src/main/java/dev/backlog/like/infra/PostLikeRepositoryAdaptor.java
  src/main/java/dev/backlog/like/infra/jpa/LikeJpaRepository.java
  src/main/java/dev/backlog/like/infra/jpa/PostLikeJpaRepository.java
  src/main/java/dev/backlog/like/service/PostLikeService.java
  src/main/java/dev/backlog/post/domain/Post.java
  src/main/java/dev/backlog/post/infra/jpa/PostJpaRepository.java
  src/main/java/dev/backlog/post/service/query/PostQueryService.java
  src/main/resources/application.yml
  src/test/java/dev/backlog/common/RepositoryTestConfig.java
  src/test/java/dev/backlog/common/config/ControllerTestConfig.java
  src/test/java/dev/backlog/common/fixture/EntityFixture.java
  src/test/java/dev/backlog/like/api/PostLikeControllerTest.java
  src/test/java/dev/backlog/like/infra/PostLikeRepositoryAdaptorTest.java
  src/test/java/dev/backlog/like/service/PostLikeServiceTest.java
  src/test/java/dev/backlog/post/domain/repository/PostQueryRepositoryTest.java
  src/test/java/dev/backlog/post/domain/repository/PostRepositoryTest.java
  src/test/java/dev/backlog/post/service/PostServiceTest.java
  src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
Labels: ✏️ Feature

#120 댓글 수정 기능 구현
  src/main/java/dev/backlog/comment/api/CommentController.java
  src/main/java/dev/backlog/comment/domain/Comment.java
  src/main/java/dev/backlog/comment/dto/CommentCreateRequest.java
  src/main/java/dev/backlog/comment/dto/CommentUpdateRequest.java
  src/main/java/dev/backlog/comment/service/CommentService.java
  src/test/java/dev/backlog/comment/api/CommentControllerTest.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
Labels: ✏️ Feature

#122 UserArgumentResolver에서 required 속성을 갖고있는 어노테이션 추가
  src/main/java/dev/backlog/auth/api/AuthController.java
  src/main/java/dev/backlog/auth/domain/oauth/JwtTokenProvider.java
  src/main/java/dev/backlog/auth/service/OAuthService.java
  src/main/java/dev/backlog/comment/api/CommentController.java
  src/main/java/dev/backlog/common/UserArgumentResolver.java
  src/main/java/dev/backlog/common/annotation/Login.java
  src/main/java/dev/backlog/like/api/PostLikeController.java
  src/main/java/dev/backlog/post/api/PostController.java
  src/main/java/dev/backlog/series/api/SeriesController.java
  src/main/java/dev/backlog/user/api/UserController.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
  src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
Labels: ✏️ Feature

#123 댓글 삭제 기능 구현
  src/main/java/dev/backlog/comment/api/CommentController.java
  src/main/java/dev/backlog/comment/domain/repository/CommentRepository.java
  src/main/java/dev/backlog/comment/infra/CommentRepositoryAdaptor.java
  src/main/java/dev/backlog/comment/service/CommentService.java
  src/test/java/dev/backlog/comment/api/CommentControllerTest.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
Labels: ✏️ Feature

#119 게시물 삭제 API, 게시물 필터 조회 API 문서화
  src/main/java/dev/backlog/like/api/PostLikeController.java
  src/main/java/dev/backlog/like/domain/PostLike.java
  src/main/java/dev/backlog/like/dto/LikeStatus.java
  src/main/java/dev/backlog/like/dto/LikeStatusResponse.java
  src/main/java/dev/backlog/like/service/PostLikeService.java
  src/main/java/dev/backlog/post/api/PostController.java
  src/main/java/dev/backlog/post/domain/Hashtag.java
  src/main/java/dev/backlog/post/domain/PostHashtag.java
  src/main/java/dev/backlog/post/service/query/PostQueryService.java
  src/main/java/dev/backlog/reply/domain/Reply.java
  src/main/java/dev/backlog/user/domain/User.java
  src/test/java/dev/backlog/like/api/PostLikeControllerTest.java
  src/test/java/dev/backlog/like/service/PostLikeServiceTest.java
  src/test/java/dev/backlog/post/api/PostControllerTest.java
  src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
Labels: ✏️ Feature

#125 깃허브 소셜 로그인 기능 구현
  src/main/java/dev/backlog/auth/domain/oauth/OAuthProvider.java
  src/main/java/dev/backlog/auth/infrastructure/github/GithubTokens.java
  src/main/java/dev/backlog/auth/infrastructure/github/authCode/GithubAuthCodeRequestUrlProvider.java
  src/main/java/dev/backlog/auth/infrastructure/github/client/GithubApiClient.java
  src/main/java/dev/backlog/auth/infrastructure/github/client/GithubMemberClient.java
  src/main/java/dev/backlog/auth/infrastructure/github/config/GithubConfig.java
  src/main/java/dev/backlog/auth/infrastructure/github/config/GithubProperties.java
  src/main/java/dev/backlog/auth/infrastructure/github/dto/GithubMemberResponse.java
  src/main/resources/application.yml
Labels: ✏️ Feature

#128 비공개 게시물 조회 시, 사용자 검증 로직 추가
  src/main/java/dev/backlog/common/config/PostAccessStrategyMapConfig.java
  src/main/java/dev/backlog/post/domain/repository/PostCacheRepository.java
  src/main/java/dev/backlog/post/infra/PostCacheRepositoryAdaptor.java
  src/main/java/dev/backlog/post/service/query/PostAccessStrategy.java
  src/main/java/dev/backlog/post/service/query/PostQueryService.java
  src/main/java/dev/backlog/post/service/query/PrivatePostAccessStrategy.java
  src/main/java/dev/backlog/post/service/query/PublicPostAccessStrategy.java
  src/test/java/dev/backlog/comment/infra/CommentRepositoryAdaptorTest.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
  src/test/java/dev/backlog/common/fixture/EntityFixture.java
  src/test/java/dev/backlog/like/infra/PostLikeRepositoryAdaptorTest.java
  src/test/java/dev/backlog/like/service/PostLikeServiceTest.java
  src/test/java/dev/backlog/post/domain/repository/PostQueryRepositoryTest.java
  src/test/java/dev/backlog/post/infra/jpa/PostHashtagJpaRepositoryTest.java
  src/test/java/dev/backlog/post/service/PostServiceTest.java
  src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
  src/test/java/dev/backlog/post/service/query/PrivatePostAccessStrategyTest.java
  src/test/java/dev/backlog/post/service/query/PublicPostAccessStrategyTest.java
Labels: ✏️ Feature, 📝 Fix

#135 Jacoco 라이브러리 적용
  build.gradle
  lombok.config
Labels: ✏️ Feature

#136 게시물 저장 시 검증 추가
  build.gradle
  src/main/java/dev/backlog/common/config/HTMLCharacterEscapes.java
  src/main/java/dev/backlog/common/config/HttpMessageConverterConfig.java
  src/main/java/dev/backlog/reply/domain/Reply.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
  src/test/java/dev/backlog/common/HTMLCharacterEscapesTest.java
Labels: ✏️ Feature

#137 대댓글 기능 구현
  src/main/java/dev/backlog/comment/api/CommentController.java
  src/main/java/dev/backlog/comment/domain/Comment.java
  src/main/java/dev/backlog/comment/dto/CommentCreateRequest.java
  src/main/java/dev/backlog/comment/service/CommentService.java
  src/main/java/dev/backlog/reply/domain/Reply.java
  src/main/java/dev/backlog/reply/infrastructure/persistence/ReplyRepository.java
  src/test/java/dev/backlog/comment/api/CommentControllerTest.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
Labels: ✏️ Feature

#141 패키지 정리
  src/main/java/dev/backlog/auth/api/AuthController.java
  src/main/java/dev/backlog/auth/dto/AuthTokens.java
  src/main/java/dev/backlog/auth/dto/AuthTokensGenerator.java
  src/main/java/dev/backlog/auth/infrastructure/github/client/GithubApiClient.java
  src/main/java/dev/backlog/auth/infrastructure/github/client/GithubMemberClient.java
  src/main/java/dev/backlog/auth/infrastructure/github/dto/GithubTokens.java
  src/main/java/dev/backlog/auth/infrastructure/kakao/client/KakaoApiClient.java
  src/main/java/dev/backlog/auth/infrastructure/kakao/client/KakaoMemberClient.java
  src/main/java/dev/backlog/auth/infrastructure/kakao/dto/KakaoTokens.java
  src/main/java/dev/backlog/auth/service/OAuthService.java
  src/main/java/dev/backlog/common/config/AuthWebConfig.java
  src/main/java/dev/backlog/common/config/UserArgumentResolver.java
  src/test/java/dev/backlog/auth/api/AuthControllerTest.java
  src/test/java/dev/backlog/auth/service/OAuthServiceTest.java
  src/test/java/dev/backlog/common/fixture/DtoFixture.java
Labels: 🧚 Refactor

#142 테스트 코드 작성
  src/main/java/dev/backlog/auth/domain/oauth/client/OAuthMemberClientComposite.java
  src/main/java/dev/backlog/auth/infrastructure/github/dto/GithubMemberResponse.java
  src/main/java/dev/backlog/user/domain/User.java
  src/test/java/dev/backlog/auth/domain/oauth/JwtTokenProviderTest.java
  src/test/java/dev/backlog/auth/domain/oauth/OAuthProviderTest.java
  src/test/java/dev/backlog/auth/domain/oauth/authcode/AuthCodeRequestUrlProviderCompositeTest.java
  src/test/java/dev/backlog/auth/domain/oauth/client/OAuthMemberClientCompositeTest.java
  src/test/java/dev/backlog/auth/dto/AuthTokensGeneratorTest.java
  src/test/java/dev/backlog/auth/infrastructure/github/authCode/GithubAuthCodeRequestUrlProviderTest.java
  src/test/java/dev/backlog/auth/infrastructure/github/client/GithubApiClientTest.java
  src/test/java/dev/backlog/auth/infrastructure/kakao/authcode/KakaoAuthCodeRequestUrlProviderTest.java
  src/test/java/dev/backlog/auth/infrastructure/kakao/client/KakaoApiClientTest.java
  src/test/java/dev/backlog/user/api/UserControllerTest.java
  src/test/java/dev/backlog/user/domain/UserTest.java
  src/test/java/dev/backlog/user/infrastructure/UserRepositoryAdapterTest.java
Labels: 🧚 Refactor

#143 테스트 코드 수정
  src/main/java/dev/backlog/auth/api/AuthController.java
  src/main/java/dev/backlog/auth/infrastructure/github/client/GithubApiClient.java
  src/main/java/dev/backlog/auth/infrastructure/github/client/GithubMemberClient.java
  src/main/java/dev/backlog/auth/infrastructure/kakao/client/KakaoApiClient.java
  src/main/java/dev/backlog/auth/infrastructure/kakao/client/KakaoMemberClient.java
  src/main/java/dev/backlog/auth/service/OAuthService.java
  src/main/java/dev/backlog/comment/api/CommentController.java
  src/main/java/dev/backlog/like/api/PostLikeController.java
  src/main/java/dev/backlog/post/api/PostController.java
  src/main/java/dev/backlog/series/api/SeriesController.java
  src/main/java/dev/backlog/user/api/UserController.java
  src/main/resources/logback.xml
  src/test/java/dev/backlog/auth/api/AuthControllerTest.java
  src/test/java/dev/backlog/auth/domain/oauth/JwtTokenProviderTest.java
  src/test/java/dev/backlog/auth/domain/oauth/OAuthProviderTest.java
  src/test/java/dev/backlog/auth/domain/oauth/authcode/AuthCodeRequestUrlProviderCompositeTest.java
  src/test/java/dev/backlog/auth/dto/AuthTokensGeneratorTest.java
  src/test/java/dev/backlog/auth/infrastructure/github/authCode/GithubAuthCodeRequestUrlProviderTest.java
  src/test/java/dev/backlog/auth/infrastructure/github/client/GithubApiClientTest.java
  src/test/java/dev/backlog/auth/infrastructure/kakao/authcode/KakaoAuthCodeRequestUrlProviderTest.java
  src/test/java/dev/backlog/auth/infrastructure/kakao/client/KakaoApiClientTest.java
  src/test/java/dev/backlog/auth/service/OAuthServiceTest.java
  src/test/java/dev/backlog/comment/api/CommentControllerTest.java
  src/test/java/dev/backlog/comment/infra/CommentRepositoryAdaptorTest.java
  src/test/java/dev/backlog/comment/service/CommentServiceTest.java
  src/test/java/dev/backlog/common/HTMLCharacterEscapesTest.java
  src/test/java/dev/backlog/common/fixture/DtoFixture.java
  src/test/java/dev/backlog/common/fixture/EntityFixture.java
  src/test/java/dev/backlog/like/api/PostLikeControllerTest.java
  src/test/java/dev/backlog/like/infra/PostLikeRepositoryAdaptorTest.java
  src/test/java/dev/backlog/like/service/PostLikeServiceTest.java
  src/test/java/dev/backlog/post/api/PostControllerTest.java
  src/test/java/dev/backlog/post/domain/repository/PostCacheRepositoryTest.java
  src/test/java/dev/backlog/post/domain/repository/PostQueryRepositoryTest.java
  src/test/java/dev/backlog/post/domain/repository/PostRepositoryTest.java
  src/test/java/dev/backlog/post/infra/jpa/HashtagRepositoryAdapterTest.java
  src/test/java/dev/backlog/post/infra/jpa/PostHashtagJpaRepositoryTest.java
  src/test/java/dev/backlog/post/service/PostServiceTest.java
  src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
  src/test/java/dev/backlog/post/service/query/PrivatePostAccessStrategyTest.java
  src/test/java/dev/backlog/post/service/query/PublicPostAccessStrategyTest.java
  src/test/java/dev/backlog/series/api/SeriesControllerTest.java
  src/test/java/dev/backlog/series/domain/repository/SeriesRepositoryTest.java
  src/test/java/dev/backlog/series/infra/SeriesRepositoryAdaptorTest.java
  src/test/java/dev/backlog/series/service/SeriesServiceTest.java
  src/test/java/dev/backlog/series/service/query/SeriesQueryServiceTest.java
  src/test/java/dev/backlog/user/api/UserControllerTest.java
  src/test/java/dev/backlog/user/domain/UserTest.java
  src/test/java/dev/backlog/user/infrastructure/UserRepositoryAdapterTest.java
  src/test/java/dev/backlog/user/service/UserServiceTest.java
Labels: 🧚 Refactor

#144 리드미 작성
  .gitignore
  README.md
  img.png
  img_1.png
  img_2.png
  img_3.png
  img_4.png
  img_5.png
  img_6.png
  img_7.png
Labels: ✏️ Feature
